### ISSUE TITLE
你的问题可以问问作者

### ISSUE THREAD

**Issue by xxdoc** [sysdzw/WebView2DemoForVb6#1]
https://www.vbforums.com/showthread.php?889202-VB6-WebView2-Binding-(Edge-Chromium)&highlight=WebView2
我用的是这个参数

Private Sub WV_NewWindowRequested(ByVal IsUserInitiated As Boolean, _
                                  IsHandled As Boolean, _
                                  ByVal URI As String, _
                                  NewWindowFeatures As RC6.cCollection)
    Dim i As Long
    Debug.Print "IsUserInitiated:"; IsUserInitiated
    Debug.Print "IsHandled:"; IsHandled
    Debug.Print "URI:"; URI

    For i = 0 To NewWindowFeatures.Count - 1
        Debug.Print NewWindowFeatures.KeyByIndex(i), NewWindowFeatures.ItemByIndex(i)
    Next
    IsHandled = True '不弹出新标签

    If flag = "xxx" Then
        xx= URI
        **WV.Navigate URI, 1**  '不知道行不行...
    
    End If

    
End Sub

**Comment by sysdzw** [comment]
用 `WV.Navigate URI, 0` 确实可以，还没注意到它竟然还有第二个参数。感谢感谢。那个作者好像不怎么管WebView2-Binding那个帖子了，看到好多人在那帖子下面好几个月前反应的问题都没得到答复，而作者今天还回复了其他帖子。估计太忙了吧。
